project:
  type: website
  render:
    - index.html

website:
  title: " Montpellier_Weather"
  site-url: https://Thiziriinfo.github.io/
  repo-url: https://github.com/Thiziriinfo/Thiziriinfo.github.io
  navbar:
    left:
      - href: index.html
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
