
project:
  type: website
  output-dir: docs
website:
  title: "Meteo_Montp"
  navbar:
    left:
      - href: meteo.qmd
        text: Home
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



