# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Quarto Publish

on:
  schedule:
    - cron: '0 7 * * *'  # Rafraîchit tous les jours à 14h
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: windows-latest  # Utilise Windows
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: ["3.11.0"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v2  # Utilise la version 2 de l'action setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: python -m pip install jupyter  # Utilise "python" au lieu de "python3"
      - run: python -m pip install -r requirements.txt  # Utilise "python" au lieu de "python3"

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
